"""advcalc E33 -- chapter 3, section 2, second part (book pp. 123-125): open
balls, what translation and scaling do to them, the unit balls of the three
norms, bounded sets, the distance from a point to a set, interior points and
open sets, the proof that an open ball is open, unions of open sets, and closed
sets. Page 125 onward is exercises 2.1 to 2.15, and E34 starts section 3.

The three unit balls are drawn from the norms rather than sketched. `_unit`
walks a circle of directions and asks each norm how far along that direction
its unit ball reaches, which is one line of code per norm and no coordinates by
hand; the assertions then check the containment the picture is about, that the
subscript one ball sits inside the subscript two ball, which sits inside the
subscript infinity one. The book's Fig. 3.2 draws the same three shapes; this
one is generated by the definitions, which is what the redraw is for.
"""
import math
import pathlib, sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[3]))
from manim import Dot, Line, Text, VGroup
from manim_lessons.lib.design_tokens import (ACCENT_A, ACCENT_B, ACCENT_C, DIM, WARN)
from manim_lessons.lessons.advcalc.arrays import ArrayArt
from manim_lessons.lessons.canonical_base import CanonicalBase, make
from manim_lessons.localization.advcalc import TOPICS_ADVCALC, FORMULAS_ADVCALC

FS_TAG = 17
STEPS = 96

NORMS = (("₁", lambda x, y: abs(x) + abs(y)),
         ("₂", lambda x, y: math.hypot(x, y)),
         ("∞", lambda x, y: max(abs(x), abs(y))))


def _reach(norm, th):
 """How far the unit ball of this norm reaches in the direction th."""
 c, s = math.cos(th), math.sin(th)
 return 1.0 / norm(c, s)


def _unit(norm, cx, cy, scale):
 """The unit ball's boundary, one point per direction, closed up."""
 pts = []
 for k in range(STEPS + 1):
  th = 2 * math.pi * k / STEPS
  r = _reach(norm, th) * scale
  pts.append([cx + r * math.cos(th), cy + r * math.sin(th), 0])
 return pts


def _blob(ox, oy, rx=1.55, ry=0.84, wob=0.34):
 """The irregular shape beats 6 and 9 use, as a closed polygon."""
 return [(ox + rx * math.cos(t / 9.0) + wob * math.cos(3 * t / 9.0),
          oy + ry * math.sin(t / 9.0) - 0.20 * math.sin(2 * t / 9.0))
         for t in range(58)]


def _inside(poly, x, y):
 """Ray casting, so that a ball can be checked against the shape it is in."""
 n, hit = len(poly), False
 for i in range(n):
  x1, y1 = poly[i]
  x2, y2 = poly[(i + 1) % n]
  if (y1 > y) != (y2 > y) and x < x1 + (y - y1) * (x2 - x1) / (y2 - y1):
   hit = not hit
 return hit


def _fit(poly, cx, cy, cap=0.60):
 """The largest ball about (cx, cy) that stays inside the shape, near enough:
 a ball drawn spilling over the edge would say the wrong thing about what a
 union of balls can pave."""
 lo, hi = 0.0, cap
 for _ in range(24):
  mid = (lo + hi) / 2
  ok = all(_inside(poly, cx + mid * math.cos(2 * math.pi * k / 24),
                   cy + mid * math.sin(2 * math.pi * k / 24)) for k in range(24))
  lo, hi = (mid, hi) if ok else (lo, mid)
 return lo * 0.94


PAVE_ORIGIN = (-2.80, 0.36)
PAVE_SEEDS = ((-0.45, 0.18), (0.55, -0.10), (-1.25, -0.05),
              (0.10, 0.42), (-0.85, 0.42), (0.90, 0.00))
_POLY = _blob(*PAVE_ORIGIN)
PAVE = [(PAVE_ORIGIN[0] + dx, PAVE_ORIGIN[1] + dy,
         _fit(_POLY, PAVE_ORIGIN[0] + dx, PAVE_ORIGIN[1] + dy))
        for dx, dy in PAVE_SEEDS]

assert all(r > 0.12 for _, _, r in PAVE), "a paving ball came out too small to see"
for _cx, _cy, _r in PAVE:
 assert all(_inside(_POLY, _cx + _r * math.cos(2 * math.pi * k / 36),
                    _cy + _r * math.sin(2 * math.pi * k / 36)) for k in range(36)), \
     "a ball drawn inside the open set is not actually inside it"


# ── what beat 3 claims, checked rather than trusted ───────────────────────
for _k in range(STEPS):
 _th = 2 * math.pi * _k / STEPS
 _r = [_reach(n, _th) for _, n in NORMS]
 assert _r[0] <= _r[1] + 1e-12 <= _r[2] + 1e-12, \
     "the unit balls do not nest the way the episode says they do"
assert abs(_reach(NORMS[0][1], math.pi / 4) - math.sqrt(2) / 2) < 1e-12, \
    "the subscript one ball should meet the diagonal at one over root two"
assert abs(_reach(NORMS[2][1], math.pi / 4) - math.sqrt(2)) < 1e-12, \
    "the subscript infinity ball should reach root two along the diagonal"


class AdvCalcE33Base(ArrayArt, CanonicalBase):
 TOPICS_SRC = TOPICS_ADVCALC
 FORMULAS_SRC = FORMULAS_ADVCALC
 AUDIO_PREFIX = "e"
 EPISODE = 33

 MODE_LABEL = {
  0: {"zh": "開球：距離小於 r 的那些點", "en": "the open ball: everything closer than r"},
  1: {"zh": "平移與縮放對球做的事", "en": "what translation and scaling do to a ball"},
  2: {"zh": "三種範數，三種單位球", "en": "three norms, three unit balls"},
  3: {"zh": "而且一個包一個", "en": "and they nest, one inside the next"},
  4: {"zh": "有界：整個裝得進某一顆球", "en": "bounded: it fits inside some ball"},
  5: {"zh": "點到集合的距離", "en": "the distance from a point to a set"},
  6: {"zh": "內點與開集", "en": "interior points, and open sets"},
  7: {"zh": "開球確實是開集", "en": "an open ball really is an open set"},
  8: {"zh": "證明就是三角不等式", "en": "the proof is the triangle inequality"},
  9: {"zh": "開集是一堆球鋪成的", "en": "an open set is paved with balls"},
  10: {"zh": "閉集：補集是開的", "en": "closed: the complement is open"},
 }

 def _ballshape(self, norm, cx, cy, scale, col, sw=2.5):
  return self._curve(_unit(norm, cx, cy, scale), col, sw=sw)

 # ── beats ─────────────────────────────────────────────────────────
 def _ball(self):
  cx, cy, R = -3.30, 0.24, 1.05
  g = VGroup(self._ballshape(NORMS[1][1], cx, cy, R, ACCENT_C),
             Dot([cx, cy, 0], radius=0.065, color=WARN),
             Text("α", font_size=FS_TAG - 2, color=WARN).move_to([cx - 0.26, cy + 0.02, 0]),
             self._arr([cx, cy, 0], [cx + R * 0.94, cy, 0], WARN, sw=2, tl=0.10),
             Text("r", font_size=FS_TAG - 2, color=WARN).move_to([cx + R * 0.5, cy + 0.24, 0]),
             Dot([cx + R * 0.55, cy + R * 0.42, 0], radius=0.055, color=ACCENT_A),
             Dot([cx + R * 1.22, cy - R * 0.55, 0], radius=0.055, color=DIM))
  rows = ((0.86, "裡面的點：距離嚴格小於 r", "inside: distance strictly less than r", ACCENT_A),
          (0.20, "邊界不算在內，所以叫開球", "the boundary is not included, hence open", ACCENT_C),
          (-0.46, "這就是上一集那個 δ 帶，換到向量空間",
           "this is the last episode's delta band, moved to a vector space", DIM))
  for y, zh, en, col in rows:
   g.add(self._mid(y, zh, en, col, FS_TAG, x=2.90, w=5.60))
  return g.add(self._mid(-1.24, "有了範數就有距離，有了距離才講得出「附近」",
                         "a norm gives distance, and distance is what nearby needs",
                         ACCENT_A, FS_TAG, w=11.9),
               self._mid(-1.78, "接下來整節都在用這一個東西",
                         "the rest of the section is built on this one object",
                         DIM, FS_TAG, w=11.9))

 def _move(self):
  g = VGroup()
  base = (-4.30, 0.28, 0.74)
  g.add(self._ballshape(NORMS[1][1], *base, ACCENT_C),
        Dot([base[0], base[1], 0], radius=0.06, color=ACCENT_C))
  shifted = (-1.90, 0.28 - 0.30, 0.74)
  g.add(self._ballshape(NORMS[1][1], *shifted, WARN),
        Dot([shifted[0], shifted[1], 0], radius=0.06, color=WARN),
        self._arr([base[0] + 0.86, base[1] - 0.12, 0],
                  [shifted[0] - 0.86, shifted[1] + 0.12, 0], DIM, sw=2, tl=0.10),
        Text("β", font_size=FS_TAG - 3, color=DIM)
        .move_to([(base[0] + shifted[0]) / 2, base[1] + 0.18, 0]))
  scaled = (1.90, 0.20, 0.74 * 1.4)
  g.add(self._ballshape(NORMS[1][1], scaled[0], scaled[1], 0.74, DIM, sw=1.6),
        self._ballshape(NORMS[1][1], *scaled, ACCENT_A),
        Dot([scaled[0], scaled[1], 0], radius=0.06, color=ACCENT_A),
        Text("c", font_size=FS_TAG - 3, color=ACCENT_A)
        .move_to([scaled[0] + 0.74 * 1.4 + 0.28, scaled[1], 0]))
  rows = ((0.72, "平移：球心跟著走，半徑不動",
           "translation: the centre moves, the radius does not", WARN),
          (0.06, "縮放：半徑乘上 | c |", "scaling: the radius is multiplied by the size of c",
           ACCENT_A))
  for y, zh, en, col in rows:
   g.add(self._mid(y, zh, en, col, FS_TAG, x=4.60, w=3.00))
  return g.add(self._mid(-1.24, "兩件事都只是把範數的公理代進定義，沒有別的內容",
                         "both are the axioms substituted into the definition, and nothing more",
                         ACCENT_A, FS_TAG, w=11.9),
               self._mid(-1.78, "所以談球時，把球心搬到原點通常不損失一般性",
                         "so a ball can usually be moved to the origin without loss",
                         DIM, FS_TAG, w=11.9))

 def _three_balls(self):
  g = VGroup()
  for cx, (name, norm), col in zip((-3.80, 0.00, 3.80), NORMS,
                                   (ACCENT_C, WARN, ACCENT_A)):
   g.add(self._ballshape(norm, cx, 0.24, 0.82, col),
         Line([cx - 1.10, 0.24, 0], [cx + 1.10, 0.24, 0], color=DIM, stroke_width=1.2),
         Line([cx, 0.24 - 1.05, 0], [cx, 0.24 + 1.05, 0], color=DIM, stroke_width=1.2),
         Text("‖ · ‖ " + name, font_size=FS_TAG - 1, color=col).move_to([cx, -1.06, 0]))
  return g.add(self._mid(-1.44, "三個形狀都是同一段程式照著範數的定義畫出來的",
                         "one routine drew all three, asking each norm how far its ball reaches",
                         DIM, FS_TAG, w=11.9),
               self._mid(-1.78, "三個都叫球，只有中間那個真的是圓的",
                         "all three are called balls and only the middle one is round",
                         ACCENT_B, FS_TAG, w=11.9))

 def _nested(self):
  cx, cy, R = -3.00, 0.20, 1.05
  g = VGroup()
  for (name, norm), col in zip(NORMS, (ACCENT_C, WARN, ACCENT_A)):
   g.add(self._ballshape(norm, cx, cy, R, col))
  # how far each ball reaches along the diagonal, read off the norms rather
  # than the picture. The formula bar already carries the two inequalities,
  # so the frame carries the numbers behind them instead.
  th = math.pi / 4
  labels = ("1 / √ 2", "1", "√ 2")
  for k, ((name, norm), col) in enumerate(zip(NORMS, (ACCENT_C, WARN, ACCENT_A))):
   r = _reach(norm, th) * R
   g.add(Dot([cx + r * math.cos(th), cy + r * math.sin(th), 0], radius=0.05, color=col),
         self._sym(0.92 - k * 0.62,
                   f"‖ · ‖ {name}        {labels[k]}", col, FS_TAG, x=2.80, w=5.00))
  return g.add(self._mid(-0.52, "範數越大，球越小——不等號方向是反過來的",
                         "a larger norm makes a smaller ball: the inequality turns around",
                         ACCENT_C, FS_TAG, x=2.80, w=5.40),
               self._mid(-1.24, "沿對角線量，三顆球到得最遠的距離差最多",
                         "along the diagonal the three reach their most different distances",
                         DIM, FS_TAG, w=11.9),
               self._mid(-1.78, "後面「有限維上所有範數等價」，具體長的就是這個樣子",
                         "the theorem that all norms agree in finite dimensions looks exactly like this",
                         ACCENT_B, FS_TAG, w=11.9))

 def _bounded(self):
  ox, oy = -1.95, 0.22
  blob = [[ox + 0.52 * math.cos(t / 9.0) + 0.16 * math.cos(3 * t / 9.0),
           oy + 0.36 * math.sin(t / 9.0) - 0.12 * math.sin(2 * t / 9.0), 0]
          for t in range(58)]
  g = VGroup(self._curve(blob + [blob[0]], ACCENT_C, sw=2.5),
             Text("A", font_size=FS_TAG - 1, color=ACCENT_C).move_to([ox, oy, 0]))
  g.add(self._ballshape(NORMS[1][1], ox, oy, 0.62, WARN, sw=2),
        Dot([ox, oy, 0], radius=0.05, color=WARN))
  g.add(self._ballshape(NORMS[1][1], -1.10, 0.16, 1.10, ACCENT_A, sw=2),
        Dot([-1.10, 0.16, 0], radius=0.06, color=ACCENT_A),
        Text("0", font_size=FS_TAG - 3, color=ACCENT_A).move_to([-0.84, 0.16, 0]))
  rows = ((0.86, "裝得進以 α 為心的球", "it fits in a ball about alpha", WARN),
          (0.20, "就一定裝得進以原點為心、半徑加大的球",
           "so it fits in one about the origin with a larger radius", ACCENT_A))
  for y, zh, en, col in rows:
   g.add(self._mid(y, zh, en, col, FS_TAG, x=3.90, w=4.20))
  return g.add(self._mid(-1.24, "半徑要加多少？加上 α 自己的範數就夠了",
                         "how much larger? by the norm of alpha itself",
                         ACCENT_C, FS_TAG, w=11.9),
               self._mid(-1.78, "這是把三角不等式反過來用一次",
                         "that is the triangle inequality, used once backwards",
                         DIM, FS_TAG, w=11.9))

 def _distance(self):
  ox, oy = -1.90, 0.18
  curve = [[ox + 1.50 + 0.55 * math.cos(1.2 + t / 12.0),
            oy + 0.92 * math.sin(0.4 + t / 12.0), 0] for t in range(26)]
  g = VGroup(self._curve(curve, ACCENT_C, sw=3),
             Text("A", font_size=FS_TAG - 1, color=ACCENT_C)
             .move_to([curve[13][0] + 0.42, curve[13][1], 0]))
  best = min(range(len(curve)),
             key=lambda k: math.hypot(curve[k][0] - ox, curve[k][1] - oy))
  r = math.hypot(curve[best][0] - ox, curve[best][1] - oy)
  g.add(self._ballshape(NORMS[1][1], ox, oy, r, WARN, sw=2),
        Dot([ox, oy, 0], radius=0.065, color=WARN),
        Text("β", font_size=FS_TAG - 2, color=WARN).move_to([ox - 0.28, oy, 0]),
        Line([ox, oy, 0], curve[best], color=ACCENT_A, stroke_width=2.5),
        Dot(curve[best], radius=0.05, color=ACCENT_A))
  rows = ((0.86, "所有距離裡的最小下界", "the greatest lower bound of all the distances",
           ACCENT_A),
          (0.20, "也就是碰不到 A 的最大的球", "the largest ball that does not touch A", WARN),
          (-0.46, "點若在 A 裡，這個距離就是零", "for a point of A the distance is zero", DIM))
  for y, zh, en, col in rows:
   g.add(self._mid(y, zh, en, col, FS_TAG, x=3.60, w=4.80))
  return g.add(self._mid(-1.24, "用最小下界而不是最小值，因為最近的點不一定存在",
                         "a greatest lower bound, not a minimum, since a nearest point need not exist",
                         ACCENT_C, FS_TAG, w=11.9),
               self._mid(-1.78, "圖上這個 A 是閉的，所以剛好碰得到",
                         "the A drawn here is closed, so here it happens to be attained",
                         DIM, FS_TAG, w=11.9))

 def _interior(self):
  ox, oy = -2.90, 0.24
  blob = [[ox + 1.35 * math.cos(t / 9.0) + 0.26 * math.cos(3 * t / 9.0),
           oy + 0.80 * math.sin(t / 9.0) - 0.20 * math.sin(2 * t / 9.0), 0]
          for t in range(58)]
  g = VGroup(self._curve(blob + [blob[0]], ACCENT_C, sw=2.5),
             Text("A", font_size=FS_TAG - 1, color=ACCENT_C).move_to([ox - 0.95, oy, 0]))
  g.add(self._ballshape(NORMS[1][1], ox + 0.20, oy + 0.05, 0.34, WARN, sw=2),
        Dot([ox + 0.20, oy + 0.05, 0], radius=0.055, color=WARN),
        Dot(blob[6], radius=0.055, color=ACCENT_A),
        self._ballshape(NORMS[1][1], blob[6][0], blob[6][1], 0.30, ACCENT_A, sw=1.6))
  rows = ((0.86, "有一顆球整個落在 A 裡：α 是內點",
           "some ball about it lies wholly inside A: an interior point", WARN),
          (0.20, "邊界上的點做不到，怎麼縮都有一半在外面",
           "a boundary point cannot: however small, half the ball is outside", ACCENT_A),
          (-0.46, "每一點都是內點，就叫開集",
           "a set all of whose points are interior is called open", ACCENT_C))
  for y, zh, en, col in rows:
   g.add(self._mid(y, zh, en, col, FS_TAG, x=3.30, w=5.00))
  return g.add(self._mid(-1.24, "「內點」說的是這一點四面八方都還在集合裡",
                         "interior means there is room on every side and still inside",
                         ACCENT_A, FS_TAG, w=11.9),
               self._mid(-1.78, "所以開集沒有把自己的邊界收進來",
                         "so an open set does not contain its own boundary",
                         DIM, FS_TAG, w=11.9))

 def _open_ball(self):
  cx, cy, R = -3.10, 0.14, 1.10
  bx, by = cx + 0.62, cy + 0.34
  d = math.hypot(bx - cx, by - cy)
  g = VGroup(self._ballshape(NORMS[1][1], cx, cy, R, ACCENT_C),
             Dot([cx, cy, 0], radius=0.06, color=ACCENT_C),
             Text("α", font_size=FS_TAG - 3, color=ACCENT_C).move_to([cx - 0.24, cy - 0.02, 0]),
             Dot([bx, by, 0], radius=0.06, color=WARN),
             Text("β", font_size=FS_TAG - 3, color=WARN).move_to([bx + 0.06, by + 0.26, 0]),
             Line([cx, cy, 0], [bx, by, 0], color=DIM, stroke_width=2),
             self._ballshape(NORMS[1][1], bx, by, R - d, WARN, sw=2))
  rows = ((0.86, "β 到球心的距離小於 r", "beta is closer to the centre than r", DIM),
          (0.20, "剩下的空間就是 r 減掉那個距離",
           "the room left over is r minus that distance", WARN),
          (-0.46, "以它為半徑的小球整個留在裡面",
           "a ball of that radius about beta stays inside", ACCENT_C))
  for y, zh, en, col in rows:
   g.add(self._mid(y, zh, en, col, FS_TAG, x=3.20, w=5.20))
  return g.add(self._mid(-1.24, "所以球裡的每一點都是內點——開球確實是開集",
                         "so every point of the ball is interior, and an open ball is open",
                         ACCENT_A, FS_TAG, w=11.9),
               self._mid(-1.78, "名字取得對，但還是要證一次",
                         "the name was well chosen, and still needs proving",
                         DIM, FS_TAG, w=11.9))

 def _triangle(self):
  cx, cy, R = -3.30, 0.16, 1.10
  bx, by = cx + 0.66, cy + 0.30
  d = math.hypot(bx - cx, by - cy)
  th = 0.75
  ex, ey = bx + (R - d) * 0.86 * math.cos(th), by + (R - d) * 0.86 * math.sin(th)
  g = VGroup(self._ballshape(NORMS[1][1], cx, cy, R, ACCENT_C),
             self._ballshape(NORMS[1][1], bx, by, R - d, WARN, sw=2),
             Dot([cx, cy, 0], radius=0.055, color=ACCENT_C),
             Dot([bx, by, 0], radius=0.055, color=WARN),
             Dot([ex, ey, 0], radius=0.055, color=ACCENT_A),
             Line([bx, by, 0], [ex, ey, 0], color=ACCENT_A, stroke_width=2.5),
             Line([cx, cy, 0], [bx, by, 0], color=DIM, stroke_width=2),
             Line([cx, cy, 0], [ex, ey, 0], color=ACCENT_A, stroke_width=1.6))
  for x, y, lab, col in ((cx - 0.24, cy - 0.04, "α", ACCENT_C),
                         (bx - 0.02, by - 0.26, "β", WARN),
                         (ex + 0.20, ey + 0.14, "ξ", ACCENT_A)):
   g.add(Text(lab, font_size=FS_TAG - 3, color=col).move_to([x, y, 0]))
  return g.add(self._sym(0.72, "‖ ξ − α ‖   ≤   ‖ ξ − β ‖  +  ‖ β − α ‖",
                         ACCENT_A, FS_TAG, x=2.80, w=5.40),
               self._sym(0.06, "<   δ   +   ( r − δ )   =   r", WARN, FS_TAG,
                         x=2.80, w=5.40),
               self._mid(-0.60, "兩段路加起來還是小於 r，所以 ξ 沒有跑出大球",
                         "the two legs still add to less than r, so xi never leaves the ball",
                         ACCENT_C, FS_TAG, x=2.80, w=5.40),
               self._mid(-1.30, "直覺很可靠，但這一行才是證明",
                         "the intuition is reliable; this line is the proof",
                         ACCENT_A, FS_TAG, w=11.9),
               self._mid(-1.78, "這一節後面每一個結果，用的都是同一個不等式",
                         "every remaining result in the section uses this same inequality",
                         DIM, FS_TAG, w=11.9))

 def _unions(self):
  poly = [[x, y, 0] for x, y in _POLY]
  g = VGroup(self._curve(poly + [poly[0]], ACCENT_C, sw=2.5))
  for bx, by, r in PAVE:
   g.add(self._ballshape(NORMS[1][1], bx, by, r, WARN, sw=1.6))
  rows = ((0.86, "開集的聯集還是開集，不管幾個",
           "a union of open sets is open, however many", ACCENT_A),
          (0.20, "而任何開集都是一堆開球的聯集",
           "and every open set is a union of open balls", WARN),
          (-0.46, "但交集不保證：無窮多顆可以縮成一個點",
           "intersections carry no such guarantee: infinitely many can meet in one point", DIM))
  for y, zh, en, col in rows:
   g.add(self._mid(y, zh, en, col, FS_TAG, x=3.30, w=5.00))
  return g.add(self._mid(-1.24, "這大概是想像開集最舒服的方式",
                         "this is probably the most comfortable way to picture an open set",
                         ACCENT_C, FS_TAG, w=11.9),
               self._mid(-1.78, "形狀可以很不規則，鋪起來還是只用球",
                         "the shape may be very irregular and is still paved with balls only",
                         DIM, FS_TAG, w=11.9))

 def _closed(self):
  ox, oy = -3.20, 0.20
  g = VGroup(self._ballshape(NORMS[1][1], ox, oy, 0.92, ACCENT_C),
             Dot([ox, oy, 0], radius=0.05, color=ACCENT_C))
  px, py = ox + 1.62, oy + 0.42
  g.add(Dot([px, py, 0], radius=0.06, color=WARN),
        Text("α", font_size=FS_TAG - 3, color=WARN).move_to([px + 0.24, py + 0.06, 0]),
        self._ballshape(NORMS[1][1], px, py, 0.42, WARN, sw=1.6),
        Line([ox, oy, 0], [px, py, 0], color=DIM, stroke_width=1.6))
  rows = ((0.86, "補集是開集的集合，就叫閉集",
           "a set whose complement is open is called closed", ACCENT_C),
          (0.20, "等價地說：外面的每一點離它都有正的距離",
           "equivalently, every point outside lies at a positive distance", WARN),
          (-0.46, "閉球是閉集，證明還是三角不等式",
           "a closed ball is closed, again by the triangle inequality", ACCENT_A))
  for y, zh, en, col in rows:
   g.add(self._mid(y, zh, en, col, FS_TAG, x=3.10, w=5.20))
  return g.add(self._mid(-1.24, "開與閉既不互斥也不窮盡，有些集合兩者都不是",
                         "open and closed are neither exclusive nor exhaustive: some sets are neither",
                         ACCENT_A, FS_TAG, w=11.9),
               self._mid(-1.78, "下一集講連續，用的還是這一集的球",
                         "next time, continuity, still built out of these balls",
                         ACCENT_B, FS_TAG, w=11.9))

 def stage(self):
  bl, mv, tb = self._ball(), self._move(), self._three_balls()
  ns, bd, ds = self._nested(), self._bounded(), self._distance()
  it, ob = self._interior(), self._open_ball()
  tr, un, cl = self._triangle(), self._unions(), self._closed()
  return [([bl], []), ([mv], [bl]), ([tb], [mv]), ([ns], [tb]),
          ([bd], [ns]), ([ds], [bd]), ([it], [ds]), ([ob], [it]),
          ([tr], [ob]), ([un], [tr]), ([cl], [un])]


AdvCalcE33ZH, AdvCalcE33EN = make(AdvCalcE33Base, "33", prefix="AdvCalcE")
