"""Compact bilingual source copy for Landau episodes 04–10."""
TOPICS = {
4: {"zh": ("自由粒子的拉格朗日量", ["沒有外力時，最簡單的粒子如何運動？", "先把一顆粒子放在一條沒有標記的直線上。", "如果把整個實驗向左或向右平移，物理結果不應該改變。", "因此 L 不能依賴粒子所在的位置，也不能偏愛某個方向。", "它只能看見粒子移動得多快；最簡單的速度量是 v²。", "在低速經典力學裡，L = ½mv²；m 是質量。", "速度越難改變，質量 m 就越大，這正是慣性。", "自由粒子的拉格朗日量，已經把慣性寫進了作用量。"]), "en": ("The Lagrangian of a free particle", ["With no external force, how should the simplest particle move?", "Place one particle on an unmarked straight line.", "If we shift the entire experiment left or right, the physical result should not change.", "So L cannot depend on where the particle is, or favor one direction over another.", "It can only see how fast the particle moves; the simplest speed quantity is v squared.", "At low speeds, classical mechanics gives L = ½mv², where m is the mass.", "The harder it is to change the speed, the larger the mass m: that is inertia.", "The free-particle Lagrangian puts inertia directly into the action."])},
5: {"zh": ("粒子系統的拉格朗日量", ["如果世界裡有很多粒子，整個系統的 L 要怎麼寫？", "彼此不作用時，每個粒子都有自己的動能；總 L 就是各部分的總和。", "有作用時，再加上只依賴相對位置的勢能，L = T − U。", "可加性讓我們能從局部粒子的運動，組合出整個系統的力學。"]), "en": ("The Lagrangian of a system of particles", ["If the world contains many particles, how do we write L for the whole system?", "When particles do not interact, each has its own kinetic energy and the total L is their sum.", "With interactions, we add a potential depending on relative positions: L = T − U.", "Additivity lets local particle motions combine into the mechanics of the whole system."])},
6: {"zh": ("能量：時間均勻性留下的守恆量", ["為什麼有些數字會在運動中保持不變？", "如果物理定律今天和明天完全相同，L 就不顯含時間。", "把 L 對速度的導數乘上速度，再減去 L，得到 E = Σ q̇∂L/∂q̇ − L。", "這個 E 就是能量；時間的均勻性，變成了能量守恆。"]), "en": ("Energy: the conserved quantity from uniform time", ["Why do some quantities stay constant during motion?", "If the laws of physics are the same today and tomorrow, L has no explicit time dependence.", "Multiply each velocity by its derivative of L, then subtract L: E = Σ q̇∂L/∂q̇ − L.", "This E is energy. Uniformity of time becomes conservation of energy."])},
7: {"zh": ("動量：空間均勻性留下的守恆量", ["如果整個空間平移一點，物理實驗會改變嗎？", "不會。空間均勻性表示 L 不在乎整體位置，只在乎相對位置。", "因此對每個座標 q，p = ∂L/∂q̇ 在沒有外力時保持不變。", "動量守恆，就是空間平移對稱性的影子。"]), "en": ("Momentum: the conserved quantity from uniform space", ["Would an experiment change if we shifted the entire laboratory?", "No. Homogeneous space means L cares about relative positions, not the absolute location.", "For each coordinate q, p = ∂L/∂q̇ stays constant when no external force acts.", "Momentum conservation is the shadow of spatial translation symmetry."])},
8: {"zh": ("質心：把整個系統看成一點", ["兩個粒子互相碰撞時，能不能找到一個更簡單的代表點？", "把每個位置乘上它的質量，再除以總質量，就得到質心 R。", "內力成對抵消，所以質心只受到外力：M R̈ = F 外。", "複雜系統的整體平移，可以先由一個質心描述。"]), "en": ("The centre of mass: one point for a whole system", ["When particles collide, can one representative point simplify the picture?", "Multiply each position by its mass and divide by total mass: that gives the centre of mass R.", "Internal forces cancel in pairs, so only external force moves it: M R̈ = F external.", "The translation of a complicated system can be described first by one centre of mass."])},
9: {"zh": ("角動量：旋轉的守恆量", ["直線平移有動量，那旋轉運動有什麼對應的數字？", "從原點到粒子的向量 r，和動量 p 做叉積，得到角動量 M = r × p。", "若外力矩為零，角動量的時間導數就是零。", "旋轉對稱性，留下角動量守恆。"]), "en": ("Angular momentum: the conserved quantity of rotation", ["Linear motion has momentum. What is its counterpart for rotation?", "Take the cross product of position r with momentum p: angular momentum M = r × p.", "When the external torque is zero, its time derivative vanishes.", "Rotational symmetry leaves us conservation of angular momentum."])},
10: {"zh": ("機械相似性：不用重新解一次", ["如果把同一個系統放大，運動還會像原來一樣嗎？", "在一維運動中，L = ½mẋ² − U(x)；能量決定速度沿著勢能曲線前進。", "改變長度、時間與能量的尺度，可以把一條軌跡變成另一條相似軌跡。", "這種機械相似性，讓我們用一個解理解一整族運動。"]), "en": ("Mechanical similarity: solve a whole family at once", ["If we scale the same system up, will its motion still resemble the original?", "For one-dimensional motion, L = ½mẋ² − U(x); energy sets the speed along the potential curve.", "Rescale length, time, and energy, and one trajectory turns into a similar trajectory.", "Mechanical similarity lets one solution explain an entire family of motions."])},
11: {"zh": ("一維運動：從能量讀出軌跡", ["只有一個自由度時，能不能不先解牛頓方程，就知道粒子怎麼走？", "對座標 x，L = ½mẋ² − U(x)，而能量 E = ½mẋ² + U(x) 保持不變。", "因此速度由能量差決定：ẋ = ±√{2[E−U(x)]/m}；只有 U(x) ≤ E 的區域允許運動。", "當 U(x) = E，速度降為零，粒子在轉向點折返；兩個轉向點之間就是有限振盪。"]), "en": ("One-dimensional motion: read the trajectory from energy", ["With only one degree of freedom, can we predict the motion without first solving Newton's equation?", "For coordinate x, L = ½mẋ² − U(x), while the conserved energy is E = ½mẋ² + U(x).", "The energy difference sets the speed: ẋ = ±√{2[E−U(x)]/m}; motion is allowed only where U(x) ≤ E.", "Where U(x) = E, the speed vanishes and the particle turns back; two turning points bound an oscillation."])},
12: {"zh": ("由週期反推勢能井", ["只量到不同能量下的振盪週期，能不能反推出粒子所在的勢能井？", "對每個能量 E，水平線會在兩個轉向點 x₁ 和 x₂ 碰到 U(x)；兩點距離就是振盪寬度。", "阿貝爾反演把週期資料變成寬度：x₂(U) − x₁(U) = [1/(π√{2m})]∫₀ᵁ T(E)/√(U−E) dE。", "週期只能決定勢能井的寬度，不能決定左右形狀；再假設勢能對稱，才得到唯一的 U(x)。"]), "en": ("Reconstructing a potential well from its period", ["If we measure only the oscillation period at different energies, can we reconstruct the particle's potential well?", "For each energy E, a horizontal line meets U(x) at two turning points, x one and x two; their separation is the oscillation width.", "Abel inversion converts period data into width: x₂(U) − x₁(U) = [1/(π√{2m})]∫₀ᵁ T(E)/√(U−E) dE.", "The period fixes the width, but not the separate left and right shapes; assuming a symmetric well makes U(x) unique."])},
13: {"zh": ("約化質量：把兩體變成一體", ["兩個互相作用的粒子，能不能化成一個粒子的運動問題？", "先分離整體質心的平移，再用 r = r₁ − r₂ 描述兩粒子的相對位置。", "相對運動的拉格朗日量是 L = ½μṙ² − U(r)，其中 μ = m₁m₂/(m₁ + m₂) 稱為約化質量。", "因此兩體問題等價於質量 μ 的單一粒子在 U(r) 中運動；求出 r(t)，就能重建兩顆粒子的軌跡。"]), "en": ("Reduced mass: turn two bodies into one", ["Can the motion of two interacting particles be reduced to a one-particle problem?", "First separate the translation of the centre of mass, then use r = r₁ − r₂ for the relative position.", "The relative Lagrangian is L = ½μṙ² − U(r), where μ = m₁m₂/(m₁ + m₂) is the reduced mass.", "The two-body problem is therefore one particle of mass μ moving in U(r); once r(t) is known, both original trajectories follow."])},
14: {"zh": ("中心力場：角動量如何決定軌道", ["當位能只依賴粒子到固定中心的距離 U(r)，力永遠沿半徑方向，這就是中心力場。", "角動量 M = r × p 保持不變，所以半徑向量始終位於垂直 M 的平面內，整條軌道必定是平面的。", "在極座標中 M = mr²φ̇；因此半徑向量在相等時間掃過相等面積，這正是克卜勒第二定律。", "徑向運動可視為一維問題，其有效位能 Ueff(r) = U(r) + M²/(2mr²)；交點 Ueff = E 決定最近與最遠距離。"]), "en": ("Central fields: how angular momentum shapes an orbit", ["When the potential depends only on distance from a fixed centre, U(r), the force is always radial: this is a central field.", "Angular momentum M = r × p is conserved, so the radius vector remains in the plane perpendicular to M and the entire orbit is planar.", "In polar coordinates M = mr²φ̇; the radius vector therefore sweeps out equal areas in equal times, which is Kepler's second law.", "Radial motion becomes a one-dimensional problem with effective potential Ueff(r) = U(r) + M²/(2mr²); intersections with E set the nearest and farthest distances."])},
15: {"zh": ("克卜勒問題：能量決定圓錐軌道", ["萬有引力的位能 U(r) = −α/r，對應平方反比的吸引力；它是最重要的中心力場之一。", "結合能量與角動量守恆，軌道可寫成 p/r = 1 + e cosφ，因此焦點位於力的中心，軌道必是圓錐曲線。", "總能量 E < 0 時是橢圓，E = 0 時是拋物線，E > 0 時是雙曲線；偏心率 e 正好區分這三種情形。", "對束縛的橢圓軌道，週期滿足 T² ∝ a³，而且只由能量、也就是半長軸 a 決定，這就是克卜勒第三定律。"]), "en": ("Kepler's problem: energy selects the conic orbit", ["The gravitational potential U(r) = −α/r produces an attractive inverse-square force, one of the most important central fields.", "Combining conservation of energy and angular momentum gives p/r = 1 + e cosφ, so the force centre is a focus and the orbit is a conic section.", "For total energy E < 0 the orbit is an ellipse, for E = 0 a parabola, and for E > 0 a hyperbola; the eccentricity e distinguishes the three cases.", "For a bound elliptical orbit, T² ∝ a³, and the period depends only on the energy, equivalently the semi-major axis a: Kepler's third law."])},
16: {"zh": ("粒子解體：守恆律預測碎片方向", ["一個靜止粒子自發解體成兩個粒子時，不必知道作用力細節，動量與能量守恆就能預測結果。", "在質心系中，兩個碎片帶著大小相等、方向相反的動量；若解體能為 ε，則 p₀ = √(2με)。", "若母粒子在實驗室中以速度 V 運動，碎片速度只是向量相加 v = V + v₀；質心系的速度球因此整體平移。", "當 V > v₀，碎片只能向前落在一個圓錐內；若最大張角是 θₘₐₓ，則 sin(θₘₐₓ) = v₀ / V。"]), "en": ("Particle disintegration: conservation predicts the fragments", ["When a particle at rest spontaneously splits into two, momentum and energy conservation predict the outcome without details of the interaction.", "In the centre-of-mass frame the fragments have equal and opposite momenta; for disintegration energy ε, their magnitude is p₀ = √(2με).", "If the parent moves through the laboratory with velocity V, each fragment velocity is simply v = V + v₀, translating the centre-of-mass velocity sphere.", "When V > v₀, a fragment can emerge only inside a forward cone. If its maximum angle is θₘₐₓ, then sin(θₘₐₓ) = v₀ / V."])},
17: {"zh": ("彈性碰撞：質心系裡只轉方向", ["彈性碰撞不改變粒子的內部狀態，因此總動量與動能在碰撞前後都保持不變。", "在質心系中，兩粒子的動量始終大小相等、方向相反；碰撞只把這對向量旋轉，長度完全不變。", "回到實驗室系，只要把質心速度 V 加回兩個碰後速度；守恆律決定可能的速度圓，但散射方向仍取決於粒子間作用力。", "若第二粒子起初靜止，它最多取得入射能量的 4m₁m₂/(m₁+m₂)²；兩個質量相等時，能量可以完全轉移。"]), "en": ("Elastic collisions: only direction changes in the centre-of-mass frame", ["An elastic collision leaves the particles' internal states unchanged, so both total momentum and kinetic energy are conserved.", "In the centre-of-mass frame the two momenta remain equal and opposite; the collision merely rotates this pair of vectors without changing their lengths.", "Returning to the laboratory means adding the centre-of-mass velocity V to both final velocities. Conservation fixes a velocity circle, while the interaction selects the scattering direction.", "If the second particle starts at rest, it can receive at most the fraction 4m₁m₂/(m₁+m₂)² of the incident energy; equal masses allow complete transfer."])},
18: {"zh": ("散射：從撞擊參數到截面", ["守恆律只能限制碰撞結果；若要算出粒子究竟偏轉多少，還必須知道中心位能 U(r) 並解出軌道。", "把兩體碰撞化成約化質量 μ 的單粒子問題後，入射軌道由無限遠速度 v∞ 與撞擊參數 b 描述。", "撞擊參數 b 是入射直線與力中心的垂直距離；角動量是 M = μ × b × v∞，能量是 E = (1/2) × μ × v∞²。", "粒子先接近中心，在最近距離 rₘᵢₙ 轉向後離開；軌道的對稱性把入射與出射漸近線連到散射角 χ。", "不同的 b 對應不同的 χ：小撞擊參數通常靠中心更近、偏轉更大，大撞擊參數則幾乎沿原方向前進。", "對均勻粒子束，落在 b 到 b + db 圓環內的粒子數與面積 2π × b × db 成正比，因此散射截面 dσ = 2π × b × db。", "把 b 寫成 χ 的函數，就得到微分截面 dσ/dΩ = [b / sin(χ)] × |db/dχ|；它把可測的角分布直接連回作用位能。"]), "en": ("Scattering: from impact parameter to cross-section", ["Conservation laws only constrain a collision. To calculate the actual deflection, we must know the central potential U(r) and solve the orbit.", "After reducing the two-body collision to one particle of reduced mass μ, the incoming orbit is described by its speed at infinity v∞ and impact parameter b.", "The impact parameter b is the perpendicular distance from the incoming line to the force centre, giving M = μ × b × v∞ and E = (1/2) × μ × v∞².", "The particle approaches the centre, turns at its closest distance rₘᵢₙ, and escapes. Orbit symmetry connects the incoming and outgoing asymptotes to the scattering angle χ.", "Different values of b produce different χ: a small impact parameter usually means a closer encounter and larger deflection, while a large b gives almost straight motion.", "For a uniform beam, particles between b and b + db occupy an annulus of area 2π × b × db, defining the cross-section dσ = 2π × b × db.", "Writing b as a function of χ gives dσ/dΩ = [b / sin(χ)] × |db/dχ|. This differential cross-section links the measured angular distribution back to the interaction potential."])},
19: {"zh": ("拉塞福公式：庫侖力的散射指紋", ["現在把散射理論用在庫侖位能 U(r) = α / r；α 的正負分別代表排斥或吸引，但力的大小都依平方反比衰減。", "對約化質量 μ、無限遠速度 v∞ 與撞擊參數 b，解出雙曲線軌道後可得 b = [α / (μ × v∞²)] × cot(χ / 2)。", "這個關係很直觀：b 越大，粒子離中心越遠，散射角 χ 越小；要產生大角度偏轉，就必須非常靠近力中心。", "把 b(χ) 代入一般截面公式，得到 dσ/dΩ = [α / (2 × μ × v∞²)]² / sin⁴(χ / 2)，這就是拉塞福散射公式。", "最醒目的特徵是 sin⁻⁴(χ / 2)：小角度事件極多，而大角度散射雖然稀少，卻提供最直接的近距離結構資訊。", "公式只含 α²，所以把庫侖力從排斥改成吸引不會改變角分布；軌道彎向相反方向，但相同角度的事件數一致。", "若散射中心遠重於入射粒子，μ 幾乎等於入射質量；測量 dσ/dΩ 隨角度與能量的變化，就能檢驗平方反比定律與中心電荷。"]), "en": ("Rutherford's formula: the fingerprint of Coulomb scattering", ["Apply scattering theory to the Coulomb potential U(r) = α / r. The sign of α distinguishes repulsion from attraction, while the force magnitude follows an inverse-square law.", "For reduced mass μ, speed at infinity v∞, and impact parameter b, the hyperbolic orbit gives b = [α / (μ × v∞²)] × cot(χ / 2).", "The relation is intuitive: a larger b keeps the particle farther from the centre and produces a smaller scattering angle χ; large deflections require a close encounter.", "Substituting b(χ) into the general cross-section gives dσ/dΩ = [α / (2 × μ × v∞²)]² / sin⁴(χ / 2), Rutherford's scattering formula.", "Its striking signature is sin⁻⁴(χ / 2): small-angle events are abundant, while rare large-angle events carry the clearest information about short-distance structure.", "Only α² appears, so changing the Coulomb force from repulsive to attractive does not change the angular distribution. The orbit bends the other way, but the event count is identical.", "When the scattering centre is much heavier than the projectile, μ is nearly the projectile mass. Measuring dσ/dΩ versus angle and energy tests the inverse-square law and central charge."])},
20: {"zh": ("小角度散射：用微擾法直接算偏轉", ["當撞擊參數 b 很大、位能很弱時，粒子只被輕輕推偏；這種小角度散射可以直接用微擾法計算，而且在實驗室系就能完成。", "把 x 軸取在入射動量方向；偏轉很小時，散射角約等於垂直方向獲得的動量除以入射動量，而入射動量是質量乘上無限遠速度。", "這個垂直動量，來自整段路徑上的橫向力對時間的積分，沿粒子的直線軌跡慢慢累積。", "因為這個積分本身已經很小，可以假設粒子沿直線等速前進；橫向力就是位能的徑向梯度乘上一個幾何因子，時間則換成沿路徑的位移。", "再把對 x 的積分換成對 r 的積分，就得到一條只依撞擊參數與位能的散射角公式。", "這條公式最實用的地方是：只要知道位能，不必解出完整軌道，就能算出散射角如何隨撞擊參數變化。", "最後把它代回一般截面公式，就得到小角度區的微分截面，這正是弱場散射最實用的近似。"]), "en": ("Small-angle scattering: deflection by perturbation", ["When the impact parameter b is large, the potential is weak and the particle is barely nudged; such small-angle scattering follows directly from perturbation, in the laboratory frame.", "Take the x-axis along the incident momentum; for a small deflection the scattering angle is roughly the transverse momentum gained divided by the incident momentum, which is mass times the speed at infinity.", "That transverse momentum is the time integral of the sideways force, built up along the particle's straight-line path.", "Since the integral is already small, we let the particle move straight at constant speed; the sideways force is the radial gradient of the potential times a geometric factor, and time turns into displacement along the path.", "Converting the x-integral into an r-integral then gives a scattering angle that depends only on the impact parameter and the potential.", "The real payoff is that knowing the potential alone yields the scattering angle as a function of impact parameter, without ever solving the full orbit.", "Substituting it back into the general cross-section gives the differential cross-section at small angles, the most useful weak-field approximation."])},
21: {"zh": ("一維自由振盪：每個穩定平衡都是簡諧", ["力學系統最常見的運動之一，就是在穩定平衡附近的小振盪；我們先看最簡單的一個自由度。", "穩定平衡對應位能的極小值；在附近把位能展開，最低階就是一個二次項，係數 k 正是位能在該點的二階導數。", "動能近似為二分之一 m 乘上速度平方，於是這個系統的拉格朗日量就是動能減位能。", "代入運動方程，得到一條線性方程：質量乘加速度，加上 k 乘位移等於零，也就是加速度正比於負的位移。", "它的解是一個簡諧振盪：位移隨時間做餘弦擺動，振幅是 a，相位裡的 α 是初相位。", "關鍵是角頻率只由系統本身決定：等於根號 k 除以 m，和振幅、初始條件都無關。", "總能量是動能加位能，算出來正比於振幅的平方，等於二分之一 m 乘上角頻率平方再乘上振幅平方。"]), "en": ("Free oscillations in one dimension: every stable equilibrium is harmonic", ["One of the most common motions in mechanics is a small oscillation about a stable equilibrium; we begin with the simplest case, a single degree of freedom.", "Stable equilibrium sits at a minimum of the potential energy; expanding around it, the leading term is quadratic, with coefficient k equal to the second derivative there.", "The kinetic energy is approximately one-half m times velocity squared, so the Lagrangian of the system is the kinetic minus the potential energy.", "Putting this into the equation of motion gives a linear equation: mass times acceleration plus k times displacement equals zero, so the acceleration is proportional to minus the displacement.", "Its solution is a harmonic oscillation: the displacement swings as a cosine in time, with amplitude a and an initial phase alpha.", "The key point is that the angular frequency is fixed by the system alone: it is the square root of k over m, independent of amplitude or initial conditions.", "The total energy is kinetic plus potential, and it works out proportional to the amplitude squared, equal to one-half m times angular frequency squared times amplitude squared."])},
22: {"zh": ("受迫振盪與共振", ["一個原本會自由振盪的系統，如果再受到一個隨時間變化的外力，運動會怎麼改變？", "在運動方程的右邊加上這個外力：質量乘加速度，加上 k 乘位移，等於外力 F(t)。", "最重要的情形是週期性外力：F(t) 以固定的驅動頻率 γ 做餘弦振盪。", "穩定之後，系統會跟著驅動頻率 γ 擺動，振幅正比於一除以固有頻率平方減驅動頻率平方。", "當驅動頻率接近固有頻率 ω，這個分母趨近於零，振幅急速放大，這就是共振。", "剛好落在共振點上，振幅不再有限，而是隨時間線性成長：位移像一個越長越大的正弦波。", "所以一般運動是兩部分疊加：系統自己的自由振盪，加上被外力牽著走的受迫振盪。"]), "en": ("Forced oscillations and resonance", ["If a system that would freely oscillate is also driven by a time-varying external force, how does its motion change?", "We add that force to the right-hand side of the equation of motion: mass times acceleration plus k times displacement equals the force F(t).", "The most important case is a periodic force: F(t) oscillates as a cosine at a fixed driving frequency gamma.", "After it settles, the system swings at the driving frequency gamma, with an amplitude proportional to one over the natural frequency squared minus the driving frequency squared.", "As the driving frequency approaches the natural frequency omega, that denominator tends to zero and the amplitude grows sharply: this is resonance.", "Exactly at resonance the amplitude is no longer finite but grows linearly in time: the displacement looks like a sine wave that keeps getting taller.", "So the general motion is a sum of two parts: the system's own free oscillation, plus the forced oscillation dragged along by the external force."])},
}

# On-screen formulas (enlarged unicode Text, shown centre-stage per beat).
# Keyed by episode -> {line_index: formula}. Language-independent.
# Only episodes listed here switch to the formula-stage layout.
FORMULAS = {
20: {
 1: "χ ≈ Δp⊥ / p        (p = m × v∞)",
 2: "Δp⊥ = ∫ F⊥ dt",
 3: "F⊥ = −(dU/dr) × (b / r)\ndt = dx / v∞",
 4: "χ = −[ 2b / (m × v∞²) ]\n      × ∫ (dU/dr) dr / √(r² − b²)",
 6: "dσ = (b / χ) × |db/dχ| × dΩ",
},
21: {
 1: "U(x) ≈ ½ k x²        (k > 0)",
 2: "L = ½ m ẋ² − ½ k x²",
 3: "m ẍ + k x = 0    →    ẍ + ω² x = 0",
 4: "x = a · cos(ω t + α)",
 5: "ω = √( k / m )",
 6: "E = ½ m ω² a²",
},
22: {
 1: "m ẍ + k x = F(t)",
 2: "F(t) = f · cos(γ t)",
 3: "x(t) = [ f / ( m (ω² − γ²) ) ] · cos(γ t)",
 4: "a(γ) = f / ( m · |ω² − γ²| )",
 5: "x(t) = ( f / (2 m ω) ) · t · sin(ω t)",
},
}
