"""Compact bilingual source copy for Landau episodes 04–10."""
TOPICS = {
4: {"zh": ("自由粒子的拉格朗日量", ["沒有外力時，最簡單的粒子如何運動？", "先把一顆粒子放在一條沒有標記的直線上。", "如果把整個實驗向左或向右平移，物理結果不應該改變。", "因此 L 不能依賴粒子所在的位置，也不能偏愛某個方向。", "它只能看見粒子移動得多快；最簡單的速度量是 v²。", "在低速經典力學裡，L = ½mv²；m 是質量。", "速度越難改變，質量 m 就越大，這正是慣性。", "自由粒子的拉格朗日量，已經把慣性寫進了作用量。"]), "en": ("The Lagrangian of a free particle", ["With no external force, how should the simplest particle move?", "Place one particle on an unmarked straight line.", "If we shift the entire experiment left or right, the physical result should not change.", "So L cannot depend on where the particle is, or favor one direction over another.", "It can only see how fast the particle moves; the simplest speed quantity is v squared.", "At low speeds, classical mechanics gives L = ½mv², where m is the mass.", "The harder it is to change the speed, the larger the mass m: that is inertia.", "The free-particle Lagrangian puts inertia directly into the action."])},
5: {"zh": ("粒子系統的拉格朗日量", ["如果世界裡有很多粒子，整個系統的 L 要怎麼寫？", "彼此不作用時，每個粒子都有自己的動能；總 L 就是各部分的總和。", "有作用時，再加上只依賴相對位置的勢能，L = T − U。", "可加性讓我們能從局部粒子的運動，組合出整個系統的力學。"]), "en": ("The Lagrangian of a system of particles", ["If the world contains many particles, how do we write L for the whole system?", "When particles do not interact, each has its own kinetic energy and the total L is their sum.", "With interactions, we add a potential depending on relative positions: L = T − U.", "Additivity lets local particle motions combine into the mechanics of the whole system."])},
6: {"zh": ("能量：時間均勻性留下的守恆量", ["為什麼有些數字會在運動中保持不變？", "如果物理定律今天和明天完全相同，L 就不顯含時間。", "把 L 對速度的導數乘上速度，再減去 L，得到 E = Σ q̇∂L/∂q̇ − L。", "這個 E 就是能量；時間的均勻性，變成了能量守恆。"]), "en": ("Energy: the conserved quantity from uniform time", ["Why do some quantities stay constant during motion?", "If the laws of physics are the same today and tomorrow, L has no explicit time dependence.", "Multiply each velocity by its derivative of L, then subtract L: E = Σ q̇∂L/∂q̇ − L.", "This E is energy. Uniformity of time becomes conservation of energy."])},
7: {"zh": ("動量：空間均勻性留下的守恆量", ["如果整個空間平移一點，物理實驗會改變嗎？", "不會。空間均勻性表示 L 不在乎整體位置，只在乎相對位置。", "因此對每個座標 q，p = ∂L/∂q̇ 在沒有外力時保持不變。", "動量守恆，就是空間平移對稱性的影子。"]), "en": ("Momentum: the conserved quantity from uniform space", ["Would an experiment change if we shifted the entire laboratory?", "No. Homogeneous space means L cares about relative positions, not the absolute location.", "For each coordinate q, p = ∂L/∂q̇ stays constant when no external force acts.", "Momentum conservation is the shadow of spatial translation symmetry."])},
8: {"zh": ("質心：把整個系統看成一點", ["兩個粒子互相碰撞時，能不能找到一個更簡單的代表點？", "把每個位置乘上它的質量，再除以總質量，就得到質心 R。", "內力成對抵消，所以質心只受到外力：M R̈ = F 外。", "複雜系統的整體平移，可以先由一個質心描述。"]), "en": ("The centre of mass: one point for a whole system", ["When particles collide, can one representative point simplify the picture?", "Multiply each position by its mass and divide by total mass: that gives the centre of mass R.", "Internal forces cancel in pairs, so only external force moves it: M R̈ = F external.", "The translation of a complicated system can be described first by one centre of mass."])},
9: {"zh": ("角動量：旋轉的守恆量", ["直線平移有動量，那旋轉運動有什麼對應的數字？", "從原點到粒子的向量 r，和動量 p 做叉積，得到角動量 M = r × p。", "若外力矩為零，角動量的時間導數就是零。", "旋轉對稱性，留下角動量守恆。"]), "en": ("Angular momentum: the conserved quantity of rotation", ["Linear motion has momentum. What is its counterpart for rotation?", "Take the cross product of position r with momentum p: angular momentum M = r × p.", "When the external torque is zero, its time derivative vanishes.", "Rotational symmetry leaves us conservation of angular momentum."])},
10: {"zh": ("機械相似性：不用重新解一次", ["如果把同一個系統放大，運動還會像原來一樣嗎？", "在一維運動中，L = ½mẋ² − U(x)；能量決定速度沿著勢能曲線前進。", "改變長度、時間與能量的尺度，可以把一條軌跡變成另一條相似軌跡。", "這種機械相似性，讓我們用一個解理解一整族運動。"]), "en": ("Mechanical similarity: solve a whole family at once", ["If we scale the same system up, will its motion still resemble the original?", "For one-dimensional motion, L = ½mẋ² − U(x); energy sets the speed along the potential curve.", "Rescale length, time, and energy, and one trajectory turns into a similar trajectory.", "Mechanical similarity lets one solution explain an entire family of motions."])},
11: {"zh": ("一維運動：從能量讀出軌跡", ["只有一個自由度時，能不能不先解牛頓方程，就知道粒子怎麼走？", "對座標 x，L = ½mẋ² − U(x)，而能量 E = ½mẋ² + U(x) 保持不變。", "因此速度由能量差決定：ẋ = ±√{2[E−U(x)]/m}；只有 U(x) ≤ E 的區域允許運動。", "當 U(x) = E，速度降為零，粒子在轉向點折返；兩個轉向點之間就是有限振盪。"]), "en": ("One-dimensional motion: read the trajectory from energy", ["With only one degree of freedom, can we predict the motion without first solving Newton's equation?", "For coordinate x, L = ½mẋ² − U(x), while the conserved energy is E = ½mẋ² + U(x).", "The energy difference sets the speed: ẋ = ±√{2[E−U(x)]/m}; motion is allowed only where U(x) ≤ E.", "Where U(x) = E, the speed vanishes and the particle turns back; two turning points bound an oscillation."])},
}
